name: base
dependencies:
- nvidia::cudatoolkit=11.3.1
- numpy
- pillow
- pip
- python=3.8
- pytorch::pytorch=1.12.0=py3.8_cuda11.3_cudnn8.3.2_0
- scipy
- tqdm
- scikit-learn
- gensim
- pandas
- pip:
  - pillow-simd
  - h5py-cache
  - configargparse
  - sacrebleu
  - rouge-score
  - datasets==2.4.0
  - transformers==4.21.0
  - pytorch-lightning==1.7.0
  - fairscale
  - deepspeed
  - accelerate
  - sentencepiece!=0.1.92
  - nltk